#!/bin/bash
#
# List all available test options
#

echo "========================================================================"
echo "GraphSSL - Available Tests"
echo "========================================================================"
echo ""
echo "QUICK TESTS (recommended first):"
echo ""
echo "  1. Quick Component Validation (~10 seconds)"
echo "     python scripts/test/quick_validation.py"
echo "     Tests: Loss functions, objectives, gradient flow"
echo ""
echo "  2. Run All Experiments (~10-30 minutes)"
echo "     bash scripts/test/run_all_tests.sh"
echo "     Tests: All 4 experiments end-to-end on CPU"
echo ""
echo "------------------------------------------------------------------------"
echo "INDIVIDUAL EXPERIMENT TESTS (~5-10 minutes each):"
echo ""
echo "  3. Test Experiment 1: Supervised Node"
echo "     bash scripts/test/test_exp1_supervised_node.sh"
echo ""
echo "  4. Test Experiment 2: Supervised Link"
echo "     bash scripts/test/test_exp2_supervised_link.sh"
echo ""
echo "  5. Test Experiment 5: GraphMAE"
echo "     bash scripts/test/test_exp5_graphmae.sh"
echo ""
echo "  6. Test Experiment 8: Combined Loss"
echo "     bash scripts/test/test_exp8_combined_loss.sh"
echo ""
echo "------------------------------------------------------------------------"
echo "UNIT TESTS:"
echo ""
echo "  7. Test Loss Functions (40 tests)"
echo "     python tests/test_loss_functions.py"
echo ""
echo "  8. Test Objectives (30 tests)"
echo "     python tests/test_objectives.py"
echo ""
echo "========================================================================"
echo "RECOMMENDED WORKFLOW:"
echo "========================================================================"
echo ""
echo "Before GPU training, run:"
echo ""
echo "  Step 1: python scripts/test/quick_validation.py"
echo "  Step 2: bash scripts/test/run_all_tests.sh"
echo "  Step 3: bash scripts/hpc/submit_all_experiments.sh"
echo ""
echo "See TESTING_GUIDE.md for detailed information."
echo ""
echo "========================================================================"

